version: "3.8"
services:
  db:
    container_name: db
    image: postgres:14.4
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: rappers
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: '--encoding=UTF8 --lc-collate=C --lc-ctype=C'
    ports:
      - "5432:5432"

  app:
    container_name: app
    build: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: bash -c "wait-for-it --service db:5432 && python main.py"

volumes:
  db_data:
  pgadmin_data: