version: "3.8"
services:

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9-management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE-secret_cookie}
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: rabbitmqhost

  db:
    container_name: db
    image: postgres:14.4
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgres-dump/dump_all.sql:/docker-entrypoint-initdb.d/dump_all.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: rappers
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: '--encoding=UTF8 --lc-collate=C --lc-ctype=C'
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    logging:
      driver: none

  app:
    container_name: app
    build: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: bash -c "wait-for-it --service db:5432 && uvicorn main:app --reload --host 0.0.0.0 --port 8000"

  celery_worker:
    container_name: celery_worker
    build: ./app
    command: bash -c "wait-for-it --service app:8000 && celery -A celery_worker worker --loglevel=info -B"
    volumes:
      - ./app:/app
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL-amqp://guest:guest@rabbitmqhost:5672//}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND-db+postgresql+psycopg2://postgres:password@db/rappers}

  flower:
    container_name: flower
    image: mher/flower:0.9.5
    ports:
      - "5566:5566"
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL-amqp://guest:guest@rabbitmqhost:5672//}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND-db+postgresql+psycopg2://postgres:password@db/rappers}
      - FLOWER_PORT=5566

volumes:
  db_data:
  pgadmin_data:
  rabbitmq_data: