"""Create table

Revision ID: 95fdbe5d74df
Revises: 
Create Date: 2022-06-28 13:13:34.793945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95fdbe5d74df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('musician',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('artistName', sa.String(length=32), nullable=True),
    sa.Column('numberOfWords10000', sa.Integer(), nullable=True),
    sa.Column('numberOfWords20000', sa.Integer(), nullable=True),
    sa.Column('numberOfWords30000', sa.Integer(), nullable=True),
    sa.Column('numberOfWordsAll', sa.Integer(), nullable=True),
    sa.Column('ranking10000', sa.Integer(), nullable=True),
    sa.Column('ranking20000', sa.Integer(), nullable=True),
    sa.Column('ranking30000', sa.Integer(), nullable=True),
    sa.Column('rankingAll', sa.Integer(), nullable=True),
    sa.Column('mostCommon10000', sa.String(length=256), nullable=True),
    sa.Column('mostCommon20000', sa.String(length=256), nullable=True),
    sa.Column('mostCommon30000', sa.String(length=256), nullable=True),
    sa.Column('mostCommonAll', sa.String(length=256), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artistName'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_musician_id'), 'musician', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_musician_id'), table_name='musician')
    op.drop_table('musician')
    # ### end Alembic commands ###
